config/routes.rb
DeviseTest::Application.routes.draw do
  resources :welcome
  resources :dashboard

  devise_for :admins, :skip => :sessions, :controllers => { :registrations => "admin/registrations" }

  devise_for :users, :controllers => {:sessions  => 'sessions'} do
      delete '/logout', :to => 'sessions#destroy', :as => :destroy_user_session
      get '/login', :to => 'sessions#new', :as => :new_user_session
      post '/login', :to => 'sessions#create', :as => :user_session
  end

  authenticated :user do
    root :to => "dashboard#index"
  end

  authenticated :admin do
    root :to => "dashboard#index"
  end

  root :to => 'welcome#index'

end

app/models/admin.rb
## Single Table Inheritance
# Admin model
class Admin < User
end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/admin/registrations_controller.rb
class Admin::RegistrationsController < Devise::RegistrationsController
  def sign_up(resource_name, resource)
    sign_in(:user, resource)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!

  # GET /dashboards
  # GET /dashboards.json
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private
  def after_sign_in_path_for(resource)
    #stored_location_for(resource) || user_url
    debugger
    root_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def create
      debugger
      sign_in(resource.type.underscore, resource.type.constantize.send(:find, resource.id)) unless resource.type.nil?
rtn = super
      rtn
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  # GET /welcomes
  # GET /welcomes.json
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/dashboard/_form.html.erb
<%= form_for(@dashboard) do |f| %>
  <% if @dashboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dashboard.errors.count, "error") %> prohibited this dashboard from being saved:</h2>

      <ul>
      <% @dashboard.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dashboard/index.html.erb
<h1>Dashboard</h1>

  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_admin_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeviseTest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/_form.html.erb
<%= form_for(@welcome) do |f| %>
  <% if @welcome.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@welcome.errors.count, "error") %> prohibited this welcome from being saved:</h2>

      <ul>
      <% @welcome.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome page</h1>

  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "sign in", new_user_session_path %>
  <% end %>

<h2>Sign up</h2>

<%= form_for(Admin.new, :as => :admin, :url => registration_path(:admin)) do |f| %>
  <%= devise_error_messages! %>

  <div><%= f.label :email %><br />
  <%= f.email_field :email, :autofocus => true %></div>

  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <div><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></div>

  <div><%= f.submit "Sign up" %></div>
<% end %>